apiVersion: v1
kind: Service
metadata:
  name: grasefull-shutdown-service
spec:
  selector:
    name: gracefull-shutdown
  ports:
    - name: http-{{ .Values.gracefullShutdown.appPort }}
      port: {{ .Values.gracefullShutdown.appPort }}
      targetPort: {{ .Values.gracefullShutdown.appPort }}
      protocol: TCP
    - name: http-actuator
      port: {{ .Values.gracefullShutdown.actuatorPort }}
      targetPort: {{ .Values.gracefullShutdown.actuatorPort }}
      protocol: TCP