server:
  port: 8080
  shutdown: graceful
  tomcat:
    accesslog:
      enabled: true
      prefix: access_log1
      directory: /tmp

spring:
  config:
    name: local-config

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8090
