server:
  port: 8080
  shutdown: graceful
  tomcat:
    accesslog:
      enabled: true
      prefix: access_log1
      directory: /tmp
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  config:
    name: local-config
  lifecycle:
    timeout-per-shutdown-phase: 1m


management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8090
